cmake_minimum_required(VERSION 3.25)
project(MinecraftGDBridge VERSION 0.1.0 LANGUAGES CXX C)
file(TO_CMAKE_PATH "${GEODE_SDK}" GEODE_SDK)
set(CMAKE_CXX_STANDARD 23)
set(GEODE_DISABLE_CLI_CALLS ON CACHE BOOL "" FORCE)
set(GEODE_DISABLE_PRECOMPILED_HEADERS ON CACHE BOOL "" FORCE)
set(GEODE_DONT_USE_CCACHE ON CACHE BOOL "" FORCE)
foreach(dep result json nontype_functional fmt asp2 arc TulipHook)
  set(CPM_${dep}_SOURCE "${GEODE_SDK}/../gd-deps/${dep}")
endforeach()
add_subdirectory("${GEODE_SDK}" sdk)
add_library(${PROJECT_NAME} SHARED src/main.cpp)
setup_geode_mod(${PROJECT_NAME})
target_link_libraries(${PROJECT_NAME} ws2_32)
target_compile_definitions(${PROJECT_NAME} PRIVATE GEODE_MOD_ID="experiment.minecraft_bridge")
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" OUTPUT_NAME "experiment.minecraft_bridge")
